### ISSUE TITLE
no pypi package

### ISSUE THREAD

**Issue by timeyyy** [BurntSushi/xpybutil#10]
Would be useful to have a pypi package, I can throw some links your way if you need some info on doing this.

**Comment by BurntSushi** [comment]
It looks like one is there already: https://pypi.python.org/pypi/uncrumpled_xpybutil/0.0.1

I personally am not interested in doing this, but i have no problems with someone else doing it.

**Comment by timeyyy** [comment]
Ok, i made that but current it has some modifications for python 3 support, i'll make a pull request and rename the package...
