### ISSUE TITLE
xcffib is missing

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [BurntSushi/xpybutil#12]
I installed this module via pip and tried running a script that used it and received an error saying xcffib module was not found. Please list this as a dependency.

**Comment by fennerm** [comment]
xpybutil is designed to work with a few different python X-bindings. `xcffib` is one of those but `xpyb` or `xpyb-ng` also work. I think `xcffib` is the only one that is still maintained but I'm hesitant to break backwards compatibility. I agree that this isn't very user friendly and I'm open to suggestions about how this could be improved. For now I'll update the README and add a more helpful error message.
